### ISSUE TITLE
Set up continuous deployment to push somewhere

### ISSUE THREAD

**Issue by eebbesen** [OpenTwinCities/site_bot#4]
Travis
* https://blog.travis-ci.com/2019-05-30-setting-up-a-ci-cd-process-on-github

Deployment:
* http://www.fabfile.org/

**Comment by wbushey** [comment]
This looks like a helpful tutorial on how to use Fabric to deploy to a remote host via SSH: https://medium.com/python-pandemonium/automate-your-deployment-and-ssh-activities-with-fabric-e59e0db17537

**Comment by wbushey** [comment]
Just pushed a tag, and it deployed as intended: https://travis-ci.org/OpenTwinCities/site_bot/jobs/597400282
