### ISSUE TITLE
Should we, can we convert this to Python 3?

### ISSUE THREAD

**Issue by eebbesen** [OpenTwinCities/site_bot#6]

**Comment by benjifs** [comment]
I just made some changes for python3. I wont submit a PR just yet just in case we don't want to update but feel free to test it from my branch: benjifs/site_bot@3d92b3611468dc8e5b13ded44b0fc5ed49fbde37

**Comment by wbushey** [comment]
#13 updated the site_bot repo to use Python 3. I've updated site_bot's deployed environment to use Python 3 and have successfully run the bot there. This appears to be done.
